on:
  push:
    branches:
      - master

env: 
  AZURE_GROUP_NAME: case.schollaart.net

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az group create -n ${{ env.AZURE_GROUP_NAME }} -l westeurope 
        az group deployment create -n ghaction -g ${{ env.AZURE_GROUP_NAME }} --template-file azuredeploy.json
      
        az storage container create --account-name "CaseSchollaartNetWeb" -n "\$web"
        az storage blob upload-batch -d "\$web" --account-name "CaseSchollaartNetWeb" -s "/srv/jekyll/_site" 
        az storage blob service-properties update --account-name "CaseSchollaartNetWeb" --static-website --index-document index.html --404-document index.html
